# Configurações do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/proli_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Configurações do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chave secreta do JWT (gerada aleatoriamente ou injetada)
api.security.token.secret=${JWT_SECRET:chave-padrao-temporaria-apenas-para-dev-local-1234567890}

# Credenciais do Administrador (para o Seeder)
admin.default.email=${ADMIN_EMAIL:admin@proli.com}
admin.default.password=${ADMIN_PASS:senhaForte123}